name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Martijn'
      - name: Log Greeting Time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
    


